// GENERATED by scripts/generate.mjs from the role manifest. Do not edit; edit roles/<slug>.json instead.
'use agent';
import { useRole } from '@org/harness';
import type { RoleManifest } from '@org/harness';
import manifest from '../../roles/agile-coach.json';
import skill_agile_scrum_playbook from '../skills/agile-scrum-playbook/SKILL.md';
import skill_org_conventions from '../skills/org-conventions/SKILL.md';
import { ScrumMaster } from './scrum-master.ts';
import { KanbanLead } from './kanban-lead.ts';
import { ReleaseTrainEngineer } from './release-train-engineer.ts';
import { AgileTransformationLead } from './agile-transformation-lead.ts';

export function AgileCoach() {
  return useRole(
    { manifest: manifest as RoleManifest, skills: [skill_agile_scrum_playbook, skill_org_conventions] },
    { team: {
      'scrum-master': { agent: ScrumMaster, name: "Scrum Master" },
      'kanban-lead': { agent: KanbanLead, name: "Kanban Lead" },
      'release-train-engineer': { agent: ReleaseTrainEngineer, name: "Release Train Engineer" },
      'agile-transformation-lead': { agent: AgileTransformationLead, name: "Agile Transformation Lead" },
    } },
  );
}
