// GENERATED by scripts/generate.mjs from the role manifest. Do not edit; edit roles/<slug>.json instead.
'use agent';
import { useRole } from '@org/harness';
import type { RoleManifest } from '@org/harness';
import manifest from '../../roles/kanban-lead.json';
import skill_agile_scrum_playbook from '../skills/agile-scrum-playbook/SKILL.md';
import skill_org_conventions from '../skills/org-conventions/SKILL.md';

export function KanbanLead() {
  return useRole(
    { manifest: manifest as RoleManifest, skills: [skill_agile_scrum_playbook, skill_org_conventions] },
  );
}
