// GENERATED by scripts/generate.mjs from the role manifest. Do not edit; edit roles/<slug>.json instead.
'use agent';
import { useRole } from '@org/harness';
import type { RoleManifest } from '@org/harness';
import manifest from '../../roles/data-engineer.json';
import skill_data_engineering_analytics_playbook from '../skills/data-engineering-analytics-playbook/SKILL.md';
import skill_org_conventions from '../skills/org-conventions/SKILL.md';

export function DataEngineer() {
  return useRole(
    { manifest: manifest as RoleManifest, skills: [skill_data_engineering_analytics_playbook, skill_org_conventions] },
  );
}
