// GENERATED by scripts/generate.mjs from the role manifest. Do not edit; edit roles/<slug>.json instead.
'use agent';
import { useRole } from '@org/harness';
import type { RoleManifest } from '@org/harness';
import manifest from '../../roles/data-engineering-manager.json';
import skill_data_engineering_analytics_playbook from '../skills/data-engineering-analytics-playbook/SKILL.md';
import skill_org_conventions from '../skills/org-conventions/SKILL.md';
import { DataEngineer } from './data-engineer.ts';
import { DataWarehouseEngineer } from './data-warehouse-engineer.ts';
import { EtlDeveloper } from './etl-developer.ts';
import { DataAnalyst } from './data-analyst.ts';
import { BusinessIntelligenceDeveloper } from './business-intelligence-developer.ts';
import { DataScientist } from './data-scientist.ts';
import { MlEngineer } from './ml-engineer.ts';
import { AnalyticsEngineer } from './analytics-engineer.ts';

export function DataEngineeringManager() {
  return useRole(
    { manifest: { ...manifest, mcp: [{"id":"github","tier":"write"}] } as RoleManifest, skills: [skill_data_engineering_analytics_playbook, skill_org_conventions] },
    { team: {
      'data-engineer': { agent: DataEngineer, name: "Data Engineer" },
      'data-warehouse-engineer': { agent: DataWarehouseEngineer, name: "Data Warehouse Engineer" },
      'etl-developer': { agent: EtlDeveloper, name: "ETL Developer" },
      'data-analyst': { agent: DataAnalyst, name: "Data Analyst" },
      'business-intelligence-developer': { agent: BusinessIntelligenceDeveloper, name: "Business Intelligence Developer" },
      'data-scientist': { agent: DataScientist, name: "Data Scientist" },
      'ml-engineer': { agent: MlEngineer, name: "ML Engineer" },
      'analytics-engineer': { agent: AnalyticsEngineer, name: "Analytics Engineer" },
    } },
  );
}
