// GENERATED by scripts/generate.mjs. Do not edit.
import { setProvider } from '@flue/runtime';
import { cloudflareBindingProvider } from '@flue/runtime/cloudflare/workers-ai';
import { createAgentRouter } from '@flue/runtime/routing';
import { requireCaller } from '@org/harness';
import { env } from 'cloudflare:workers';
import { Hono } from 'hono';
import { DocumentationManager } from './agents/documentation-manager.ts';
import { TechnicalWriter } from './agents/technical-writer.ts';
import { ApiDocumentationSpecialist } from './agents/api-documentation-specialist.ts';
import { KnowledgeBaseManager } from './agents/knowledge-base-manager.ts';
import { VideoTutorialCreator } from './agents/video-tutorial-creator.ts';
import { InformationDeveloper } from './agents/information-developer.ts';
import { ContentStrategist } from './agents/content-strategist.ts';

// Every model call goes through this department's own AI Gateway (budgets, logs, rate limits).
setProvider(
  cloudflareBindingProvider({
    binding: env.AI,
    gateway: { id: "dept-documentation-technical-writing", metadata: { department: "documentation-technical-writing" } },
  }),
);

const app = new Hono();
app.get('/healthz', (c) => c.text('ok'));
app.use('/agents/*', requireCaller());
app.route('/agents/documentation-manager', createAgentRouter(DocumentationManager));
app.route('/agents/technical-writer', createAgentRouter(TechnicalWriter));
app.route('/agents/api-documentation-specialist', createAgentRouter(ApiDocumentationSpecialist));
app.route('/agents/knowledge-base-manager', createAgentRouter(KnowledgeBaseManager));
app.route('/agents/video-tutorial-creator', createAgentRouter(VideoTutorialCreator));
app.route('/agents/information-developer', createAgentRouter(InformationDeveloper));
app.route('/agents/content-strategist', createAgentRouter(ContentStrategist));

export default app;
