// GENERATED by scripts/generate.mjs. Do not edit.
import { setProvider } from '@flue/runtime';
import { cloudflareBindingProvider } from '@flue/runtime/cloudflare/workers-ai';
import { createAgentRouter } from '@flue/runtime/routing';
import { requireCaller } from '@org/harness';
import { env } from 'cloudflare:workers';
import { Hono } from 'hono';
import { AgileCoach } from './agents/agile-coach.ts';
import { ScrumMaster } from './agents/scrum-master.ts';
import { KanbanLead } from './agents/kanban-lead.ts';
import { ReleaseTrainEngineer } from './agents/release-train-engineer.ts';
import { AgileTransformationLead } from './agents/agile-transformation-lead.ts';

// Every model call goes through this department's own AI Gateway (budgets, logs, rate limits).
setProvider(
  cloudflareBindingProvider({
    binding: env.AI,
    gateway: { id: "dept-agile-scrum", metadata: { department: "agile-scrum" } },
  }),
);

const app = new Hono();
app.get('/healthz', (c) => c.text('ok'));
app.use('/agents/*', requireCaller());
app.route('/agents/agile-coach', createAgentRouter(AgileCoach));
app.route('/agents/scrum-master', createAgentRouter(ScrumMaster));
app.route('/agents/kanban-lead', createAgentRouter(KanbanLead));
app.route('/agents/release-train-engineer', createAgentRouter(ReleaseTrainEngineer));
app.route('/agents/agile-transformation-lead', createAgentRouter(AgileTransformationLead));

export default app;
