// GENERATED by scripts/generate.mjs. Do not edit.
import { setProvider } from '@flue/runtime';
import { cloudflareBindingProvider } from '@flue/runtime/cloudflare/workers-ai';
import { createAgentRouter } from '@flue/runtime/routing';
import { requireCaller } from '@org/harness';
import { env } from 'cloudflare:workers';
import { Hono } from 'hono';
import { VpOfSales } from './agents/vp-of-sales.ts';
import { SalesDevelopmentRepSdr } from './agents/sales-development-rep-sdr.ts';
import { AccountExecutive } from './agents/account-executive.ts';
import { EnterpriseSalesRep } from './agents/enterprise-sales-rep.ts';
import { SolutionsEngineerSalesEngineer } from './agents/solutions-engineer-sales-engineer.ts';
import { CustomerSuccessManager } from './agents/customer-success-manager.ts';
import { AccountManager } from './agents/account-manager.ts';
import { SalesOperationsAnalyst } from './agents/sales-operations-analyst.ts';
import { RevenueOperationsManager } from './agents/revenue-operations-manager.ts';

// Every model call goes through this department's own AI Gateway (budgets, logs, rate limits).
setProvider(
  cloudflareBindingProvider({
    binding: env.AI,
    gateway: { id: "dept-sales", metadata: { department: "sales" } },
  }),
);

const app = new Hono();
app.get('/healthz', (c) => c.text('ok'));
app.use('/agents/*', requireCaller());
app.route('/agents/vp-of-sales', createAgentRouter(VpOfSales));
app.route('/agents/sales-development-rep-sdr', createAgentRouter(SalesDevelopmentRepSdr));
app.route('/agents/account-executive', createAgentRouter(AccountExecutive));
app.route('/agents/enterprise-sales-rep', createAgentRouter(EnterpriseSalesRep));
app.route('/agents/solutions-engineer-sales-engineer', createAgentRouter(SolutionsEngineerSalesEngineer));
app.route('/agents/customer-success-manager', createAgentRouter(CustomerSuccessManager));
app.route('/agents/account-manager', createAgentRouter(AccountManager));
app.route('/agents/sales-operations-analyst', createAgentRouter(SalesOperationsAnalyst));
app.route('/agents/revenue-operations-manager', createAgentRouter(RevenueOperationsManager));

export default app;
