// GENERATED by scripts/generate.mjs from the role manifest. Do not edit; edit roles/<slug>.json instead.
'use agent';
import { useRole } from '@org/harness';
import type { RoleManifest } from '@org/harness';
import manifest from '../../roles/revenue-operations-manager.json';
import skill_sales_playbook from '../skills/sales-playbook/SKILL.md';
import skill_org_conventions from '../skills/org-conventions/SKILL.md';

export function RevenueOperationsManager() {
  return useRole(
    { manifest: { ...manifest, mcp: [] } as RoleManifest, skills: [skill_sales_playbook, skill_org_conventions] },
  );
}
