// GENERATED by scripts/generate.mjs from the role manifest. Do not edit; edit roles/<slug>.json instead.
'use agent';
import { useRole } from '@org/harness';
import type { RoleManifest } from '@org/harness';
import manifest from '../../roles/vp-of-sales.json';
import skill_sales_playbook from '../skills/sales-playbook/SKILL.md';
import skill_org_conventions from '../skills/org-conventions/SKILL.md';
import { SalesDevelopmentRepSdr } from './sales-development-rep-sdr.ts';
import { AccountExecutive } from './account-executive.ts';
import { EnterpriseSalesRep } from './enterprise-sales-rep.ts';
import { SolutionsEngineerSalesEngineer } from './solutions-engineer-sales-engineer.ts';
import { CustomerSuccessManager } from './customer-success-manager.ts';
import { AccountManager } from './account-manager.ts';
import { SalesOperationsAnalyst } from './sales-operations-analyst.ts';
import { RevenueOperationsManager } from './revenue-operations-manager.ts';

export function VpOfSales() {
  return useRole(
    { manifest: { ...manifest, mcp: [] } as RoleManifest, skills: [skill_sales_playbook, skill_org_conventions] },
    { team: {
      'sales-development-rep-sdr': { agent: SalesDevelopmentRepSdr, name: "Sales Development Rep (SDR)" },
      'account-executive': { agent: AccountExecutive, name: "Account Executive" },
      'enterprise-sales-rep': { agent: EnterpriseSalesRep, name: "Enterprise Sales Rep" },
      'solutions-engineer-sales-engineer': { agent: SolutionsEngineerSalesEngineer, name: "Solutions Engineer/Sales Engineer" },
      'customer-success-manager': { agent: CustomerSuccessManager, name: "Customer Success Manager" },
      'account-manager': { agent: AccountManager, name: "Account Manager" },
      'sales-operations-analyst': { agent: SalesOperationsAnalyst, name: "Sales Operations Analyst" },
      'revenue-operations-manager': { agent: RevenueOperationsManager, name: "Revenue Operations Manager" },
    } },
  );
}
