// GENERATED by scripts/generate.mjs from the role manifest. Do not edit; edit roles/<slug>.json instead.
'use agent';
import { useRole } from '@org/harness';
import type { RoleManifest } from '@org/harness';
import manifest from '../../roles/chief-marketing-officer.json';
import skill_marketing_playbook from '../skills/marketing-playbook/SKILL.md';
import skill_org_conventions from '../skills/org-conventions/SKILL.md';
import { ProductMarketingManager } from './product-marketing-manager.ts';
import { ContentMarketingManager } from './content-marketing-manager.ts';
import { DigitalMarketingSpecialist } from './digital-marketing-specialist.ts';
import { GrowthMarketer } from './growth-marketer.ts';
import { EmailMarketingSpecialist } from './email-marketing-specialist.ts';
import { MarketingAnalyst } from './marketing-analyst.ts';
import { BrandManager } from './brand-manager.ts';
import { EventMarketingManager } from './event-marketing-manager.ts';
import { PartnerMarketingManager } from './partner-marketing-manager.ts';

export function ChiefMarketingOfficer() {
  return useRole(
    { manifest: manifest as RoleManifest, skills: [skill_marketing_playbook, skill_org_conventions] },
    { team: {
      'product-marketing-manager': { agent: ProductMarketingManager, name: "Product Marketing Manager" },
      'content-marketing-manager': { agent: ContentMarketingManager, name: "Content Marketing Manager" },
      'digital-marketing-specialist': { agent: DigitalMarketingSpecialist, name: "Digital Marketing Specialist" },
      'growth-marketer': { agent: GrowthMarketer, name: "Growth Marketer" },
      'email-marketing-specialist': { agent: EmailMarketingSpecialist, name: "Email Marketing Specialist" },
      'marketing-analyst': { agent: MarketingAnalyst, name: "Marketing Analyst" },
      'brand-manager': { agent: BrandManager, name: "Brand Manager" },
      'event-marketing-manager': { agent: EventMarketingManager, name: "Event Marketing Manager" },
      'partner-marketing-manager': { agent: PartnerMarketingManager, name: "Partner Marketing Manager" },
    } },
  );
}
