// GENERATED by scripts/generate.mjs from the role manifest. Do not edit; edit roles/<slug>.json instead.
'use agent';
import { useRole } from '@org/harness';
import type { RoleManifest } from '@org/harness';
import manifest from '../../roles/chief-product-officer.json';
import skill_product_management_strategy_playbook from '../skills/product-management-strategy-playbook/SKILL.md';
import skill_org_conventions from '../skills/org-conventions/SKILL.md';
import { ProductManager } from './product-manager.ts';
import { AssociateProductManager } from './associate-product-manager.ts';
import { ProductOwner } from './product-owner.ts';
import { ProductAnalyst } from './product-analyst.ts';
import { CompetitiveAnalyst } from './competitive-analyst.ts';
import { ProductOperations } from './product-operations.ts';

export function ChiefProductOfficer() {
  return useRole(
    { manifest: manifest as RoleManifest, skills: [skill_product_management_strategy_playbook, skill_org_conventions] },
    { team: {
      'product-manager': { agent: ProductManager, name: "Product Manager" },
      'associate-product-manager': { agent: AssociateProductManager, name: "Associate Product Manager" },
      'product-owner': { agent: ProductOwner, name: "Product Owner" },
      'product-analyst': { agent: ProductAnalyst, name: "Product Analyst" },
      'competitive-analyst': { agent: CompetitiveAnalyst, name: "Competitive Analyst" },
      'product-operations': { agent: ProductOperations, name: "Product Operations" },
    } },
  );
}
