// GENERATED by scripts/generate.mjs from the role manifest. Do not edit; edit roles/<slug>.json instead.
'use agent';
import { useRole } from '@org/harness';
import type { RoleManifest } from '@org/harness';
import manifest from '../../roles/qa-manager.json';
import skill_quality_assurance_testing_playbook from '../skills/quality-assurance-testing-playbook/SKILL.md';
import skill_org_conventions from '../skills/org-conventions/SKILL.md';
import { QaEngineer } from './qa-engineer.ts';
import { ManualTester } from './manual-tester.ts';
import { TestAutomationEngineer } from './test-automation-engineer.ts';
import { PerformanceTester } from './performance-tester.ts';
import { SecurityTester } from './security-tester.ts';
import { MobileQaSpecialist } from './mobile-qa-specialist.ts';
import { ApiIntegrationTester } from './api-integration-tester.ts';
import { RegressionTester } from './regression-tester.ts';
import { UatCoordinator } from './uat-coordinator.ts';

export function QaManager() {
  return useRole(
    { manifest: manifest as RoleManifest, skills: [skill_quality_assurance_testing_playbook, skill_org_conventions] },
    { team: {
      'qa-engineer': { agent: QaEngineer, name: "QA Engineer" },
      'manual-tester': { agent: ManualTester, name: "Manual Tester" },
      'test-automation-engineer': { agent: TestAutomationEngineer, name: "Test Automation Engineer" },
      'performance-tester': { agent: PerformanceTester, name: "Performance Tester" },
      'security-tester': { agent: SecurityTester, name: "Security Tester" },
      'mobile-qa-specialist': { agent: MobileQaSpecialist, name: "Mobile QA Specialist" },
      'api-integration-tester': { agent: ApiIntegrationTester, name: "API/Integration Tester" },
      'regression-tester': { agent: RegressionTester, name: "Regression Tester" },
      'uat-coordinator': { agent: UatCoordinator, name: "UAT Coordinator" },
    } },
  );
}
