// GENERATED by scripts/generate.mjs from the role manifest. Do not edit; edit roles/<slug>.json instead.
'use agent';
import { useRole } from '@org/harness';
import type { RoleManifest } from '@org/harness';
import manifest from '../../roles/security-tester.json';
import skill_quality_assurance_testing_playbook from '../skills/quality-assurance-testing-playbook/SKILL.md';
import skill_org_conventions from '../skills/org-conventions/SKILL.md';

export function SecurityTester() {
  return useRole(
    { manifest: manifest as RoleManifest, skills: [skill_quality_assurance_testing_playbook, skill_org_conventions] },
  );
}
