// GENERATED by scripts/generate.mjs. Do not edit.
import { setProvider } from '@flue/runtime';
import { cloudflareBindingProvider } from '@flue/runtime/cloudflare/workers-ai';
import { createAgentRouter } from '@flue/runtime/routing';
import { requireCaller } from '@org/harness';
import { env } from 'cloudflare:workers';
import { Hono } from 'hono';
import { DevopsManager } from './agents/devops-manager.ts';
import { DevopsEngineer } from './agents/devops-engineer.ts';
import { SiteReliabilityEngineerSre } from './agents/site-reliability-engineer-sre.ts';
import { CloudEngineer } from './agents/cloud-engineer.ts';
import { PlatformEngineer } from './agents/platform-engineer.ts';
import { ReleaseManager } from './agents/release-manager.ts';
import { InfrastructureEngineer } from './agents/infrastructure-engineer.ts';
import { CiCdEngineer } from './agents/ci-cd-engineer.ts';
import { ConfigurationManager } from './agents/configuration-manager.ts';
import { MonitoringObservabilityEngineer } from './agents/monitoring-observability-engineer.ts';

// Every model call goes through this department's own AI Gateway (budgets, logs, rate limits).
setProvider(
  cloudflareBindingProvider({
    binding: env.AI,
    gateway: { id: "dept-devops-infrastructure", metadata: { department: "devops-infrastructure" } },
  }),
);

const app = new Hono();
app.get('/healthz', (c) => c.text('ok'));
app.use('/agents/*', requireCaller());
app.route('/agents/devops-manager', createAgentRouter(DevopsManager));
app.route('/agents/devops-engineer', createAgentRouter(DevopsEngineer));
app.route('/agents/site-reliability-engineer-sre', createAgentRouter(SiteReliabilityEngineerSre));
app.route('/agents/cloud-engineer', createAgentRouter(CloudEngineer));
app.route('/agents/platform-engineer', createAgentRouter(PlatformEngineer));
app.route('/agents/release-manager', createAgentRouter(ReleaseManager));
app.route('/agents/infrastructure-engineer', createAgentRouter(InfrastructureEngineer));
app.route('/agents/ci-cd-engineer', createAgentRouter(CiCdEngineer));
app.route('/agents/configuration-manager', createAgentRouter(ConfigurationManager));
app.route('/agents/monitoring-observability-engineer', createAgentRouter(MonitoringObservabilityEngineer));

export default app;
