// GENERATED by scripts/generate.mjs. Do not edit.
import { setProvider } from '@flue/runtime';
import { cloudflareBindingProvider } from '@flue/runtime/cloudflare/workers-ai';
import { createAgentRouter } from '@flue/runtime/routing';
import { requireCaller } from '@org/harness';
import { env } from 'cloudflare:workers';
import { Hono } from 'hono';
import { HeadOfSupport } from './agents/head-of-support.ts';
import { CustomerSupportRepTier1 } from './agents/customer-support-rep-tier-1.ts';
import { TechnicalSupportEngineerTier2 } from './agents/technical-support-engineer-tier-2.ts';
import { SeniorSupportEngineerTier3 } from './agents/senior-support-engineer-tier-3.ts';
import { SupportOperationsManager } from './agents/support-operations-manager.ts';
import { CommunityManager } from './agents/community-manager.ts';
import { CustomerAdvocate } from './agents/customer-advocate.ts';
import { OnboardingSpecialist } from './agents/onboarding-specialist.ts';
import { TrainingSpecialist } from './agents/training-specialist.ts';

// Every model call goes through this department's own AI Gateway (budgets, logs, rate limits).
setProvider(
  cloudflareBindingProvider({
    binding: env.AI,
    gateway: { id: "dept-customer-support", metadata: { department: "customer-support" } },
  }),
);

const app = new Hono();
app.get('/healthz', (c) => c.text('ok'));
app.use('/agents/*', requireCaller());
app.route('/agents/head-of-support', createAgentRouter(HeadOfSupport));
app.route('/agents/customer-support-rep-tier-1', createAgentRouter(CustomerSupportRepTier1));
app.route('/agents/technical-support-engineer-tier-2', createAgentRouter(TechnicalSupportEngineerTier2));
app.route('/agents/senior-support-engineer-tier-3', createAgentRouter(SeniorSupportEngineerTier3));
app.route('/agents/support-operations-manager', createAgentRouter(SupportOperationsManager));
app.route('/agents/community-manager', createAgentRouter(CommunityManager));
app.route('/agents/customer-advocate', createAgentRouter(CustomerAdvocate));
app.route('/agents/onboarding-specialist', createAgentRouter(OnboardingSpecialist));
app.route('/agents/training-specialist', createAgentRouter(TrainingSpecialist));

export default app;
