// GENERATED by scripts/generate.mjs. Do not edit.
import { setProvider } from '@flue/runtime';
import { cloudflareBindingProvider } from '@flue/runtime/cloudflare/workers-ai';
import { createAgentRouter } from '@flue/runtime/routing';
import { requireCaller } from '@org/harness';
import { env } from 'cloudflare:workers';
import { Hono } from 'hono';
import { FullStackLead } from './agents/full-stack-lead.ts';
import { FullStackDeveloper } from './agents/full-stack-developer.ts';
import { MeanMernStackDeveloper } from './agents/mean-mern-stack-developer.ts';
import { RapidPrototyper } from './agents/rapid-prototyper.ts';

// Every model call goes through this department's own AI Gateway (budgets, logs, rate limits).
setProvider(
  cloudflareBindingProvider({
    binding: env.AI,
    gateway: { id: "dept-full-stack-development", metadata: { department: "full-stack-development" } },
  }),
);

const app = new Hono();
app.get('/healthz', (c) => c.text('ok'));
app.use('/agents/*', requireCaller());
app.route('/agents/full-stack-lead', createAgentRouter(FullStackLead));
app.route('/agents/full-stack-developer', createAgentRouter(FullStackDeveloper));
app.route('/agents/mean-mern-stack-developer', createAgentRouter(MeanMernStackDeveloper));
app.route('/agents/rapid-prototyper', createAgentRouter(RapidPrototyper));

export default app;
