// GENERATED by scripts/generate.mjs. Do not edit.
import { setProvider } from '@flue/runtime';
import { cloudflareBindingProvider } from '@flue/runtime/cloudflare/workers-ai';
import { createAgentRouter } from '@flue/runtime/routing';
import { requireCaller } from '@org/harness';
import { env } from 'cloudflare:workers';
import { Hono } from 'hono';
import { MobileLead } from './agents/mobile-lead.ts';
import { IosDeveloper } from './agents/ios-developer.ts';
import { AndroidDeveloper } from './agents/android-developer.ts';
import { ReactNativeDeveloper } from './agents/react-native-developer.ts';
import { FlutterDeveloper } from './agents/flutter-developer.ts';
import { MobileUiUxDeveloper } from './agents/mobile-ui-ux-developer.ts';
import { MobileDevopsEngineer } from './agents/mobile-devops-engineer.ts';

// Every model call goes through this department's own AI Gateway (budgets, logs, rate limits).
setProvider(
  cloudflareBindingProvider({
    binding: env.AI,
    gateway: { id: "dept-mobile-development", metadata: { department: "mobile-development" } },
  }),
);

const app = new Hono();
app.get('/healthz', (c) => c.text('ok'));
app.use('/agents/*', requireCaller());
app.route('/agents/mobile-lead', createAgentRouter(MobileLead));
app.route('/agents/ios-developer', createAgentRouter(IosDeveloper));
app.route('/agents/android-developer', createAgentRouter(AndroidDeveloper));
app.route('/agents/react-native-developer', createAgentRouter(ReactNativeDeveloper));
app.route('/agents/flutter-developer', createAgentRouter(FlutterDeveloper));
app.route('/agents/mobile-ui-ux-developer', createAgentRouter(MobileUiUxDeveloper));
app.route('/agents/mobile-devops-engineer', createAgentRouter(MobileDevopsEngineer));

export default app;
