// GENERATED by scripts/generate.mjs. Do not edit.
import { setProvider } from '@flue/runtime';
import { cloudflareBindingProvider } from '@flue/runtime/cloudflare/workers-ai';
import { createAgentRouter } from '@flue/runtime/routing';
import { requireCaller } from '@org/harness';
import { env } from 'cloudflare:workers';
import { Hono } from 'hono';
import { ChiefProductOfficer } from './agents/chief-product-officer.ts';
import { ProductManager } from './agents/product-manager.ts';
import { AssociateProductManager } from './agents/associate-product-manager.ts';
import { ProductOwner } from './agents/product-owner.ts';
import { ProductAnalyst } from './agents/product-analyst.ts';
import { CompetitiveAnalyst } from './agents/competitive-analyst.ts';
import { ProductOperations } from './agents/product-operations.ts';

// Every model call goes through this department's own AI Gateway (budgets, logs, rate limits).
setProvider(
  cloudflareBindingProvider({
    binding: env.AI,
    gateway: { id: "dept-product-management-strategy", metadata: { department: "product-management-strategy" } },
  }),
);

const app = new Hono();
app.get('/healthz', (c) => c.text('ok'));
app.use('/agents/*', requireCaller());
app.route('/agents/chief-product-officer', createAgentRouter(ChiefProductOfficer));
app.route('/agents/product-manager', createAgentRouter(ProductManager));
app.route('/agents/associate-product-manager', createAgentRouter(AssociateProductManager));
app.route('/agents/product-owner', createAgentRouter(ProductOwner));
app.route('/agents/product-analyst', createAgentRouter(ProductAnalyst));
app.route('/agents/competitive-analyst', createAgentRouter(CompetitiveAnalyst));
app.route('/agents/product-operations', createAgentRouter(ProductOperations));

export default app;
