// GENERATED by scripts/generate.mjs from the role manifest. Do not edit; edit roles/<slug>.json instead.
'use agent';
import { useRole } from '@org/harness';
import type { RoleManifest } from '@org/harness';
import manifest from '../../roles/contract-manager.json';
import skill_legal_compliance_playbook from '../skills/legal-compliance-playbook/SKILL.md';
import skill_org_conventions from '../skills/org-conventions/SKILL.md';

export function ContractManager() {
  return useRole(
    { manifest: { ...manifest, mcp: [] } as RoleManifest, skills: [skill_legal_compliance_playbook, skill_org_conventions] },
  );
}
