// GENERATED by scripts/generate.mjs from the role manifest. Do not edit; edit roles/<slug>.json instead.
'use agent';
import { useRole } from '@org/harness';
import type { RoleManifest } from '@org/harness';
import manifest from '../../roles/general-counsel.json';
import skill_legal_compliance_playbook from '../skills/legal-compliance-playbook/SKILL.md';
import skill_org_conventions from '../skills/org-conventions/SKILL.md';
import { CorporateLawyer } from './corporate-lawyer.ts';
import { PrivacyOfficer } from './privacy-officer.ts';
import { IntellectualPropertyAttorney } from './intellectual-property-attorney.ts';
import { ComplianceManager } from './compliance-manager.ts';
import { ContractManager } from './contract-manager.ts';
import { Paralegal } from './paralegal.ts';

export function GeneralCounsel() {
  return useRole(
    { manifest: { ...manifest, mcp: [] } as RoleManifest, skills: [skill_legal_compliance_playbook, skill_org_conventions] },
    { team: {
      'corporate-lawyer': { agent: CorporateLawyer, name: "Corporate Lawyer" },
      'privacy-officer': { agent: PrivacyOfficer, name: "Privacy Officer" },
      'intellectual-property-attorney': { agent: IntellectualPropertyAttorney, name: "Intellectual Property Attorney" },
      'compliance-manager': { agent: ComplianceManager, name: "Compliance Manager" },
      'contract-manager': { agent: ContractManager, name: "Contract Manager" },
      'paralegal': { agent: Paralegal, name: "Paralegal" },
    } },
  );
}
