// GENERATED by scripts/generate.mjs. Do not edit.
import { setProvider } from '@flue/runtime';
import { cloudflareBindingProvider } from '@flue/runtime/cloudflare/workers-ai';
import { createAgentRouter } from '@flue/runtime/routing';
import { requireCaller } from '@org/harness';
import { env } from 'cloudflare:workers';
import { Hono } from 'hono';
import { ChiefMarketingOfficer } from './agents/chief-marketing-officer.ts';
import { ProductMarketingManager } from './agents/product-marketing-manager.ts';
import { ContentMarketingManager } from './agents/content-marketing-manager.ts';
import { DigitalMarketingSpecialist } from './agents/digital-marketing-specialist.ts';
import { GrowthMarketer } from './agents/growth-marketer.ts';
import { EmailMarketingSpecialist } from './agents/email-marketing-specialist.ts';
import { MarketingAnalyst } from './agents/marketing-analyst.ts';
import { BrandManager } from './agents/brand-manager.ts';
import { EventMarketingManager } from './agents/event-marketing-manager.ts';
import { PartnerMarketingManager } from './agents/partner-marketing-manager.ts';

// Every model call goes through this department's own AI Gateway (budgets, logs, rate limits).
setProvider(
  cloudflareBindingProvider({
    binding: env.AI,
    gateway: { id: "dept-marketing", metadata: { department: "marketing" } },
  }),
);

const app = new Hono();
app.get('/healthz', (c) => c.text('ok'));
app.use('/agents/*', requireCaller());
app.route('/agents/chief-marketing-officer', createAgentRouter(ChiefMarketingOfficer));
app.route('/agents/product-marketing-manager', createAgentRouter(ProductMarketingManager));
app.route('/agents/content-marketing-manager', createAgentRouter(ContentMarketingManager));
app.route('/agents/digital-marketing-specialist', createAgentRouter(DigitalMarketingSpecialist));
app.route('/agents/growth-marketer', createAgentRouter(GrowthMarketer));
app.route('/agents/email-marketing-specialist', createAgentRouter(EmailMarketingSpecialist));
app.route('/agents/marketing-analyst', createAgentRouter(MarketingAnalyst));
app.route('/agents/brand-manager', createAgentRouter(BrandManager));
app.route('/agents/event-marketing-manager', createAgentRouter(EventMarketingManager));
app.route('/agents/partner-marketing-manager', createAgentRouter(PartnerMarketingManager));

export default app;
