// GENERATED by scripts/generate.mjs. Do not edit.
import { setProvider } from '@flue/runtime';
import { cloudflareBindingProvider } from '@flue/runtime/cloudflare/workers-ai';
import { createAgentRouter } from '@flue/runtime/routing';
import { requireCaller } from '@org/harness';
import { env } from 'cloudflare:workers';
import { Hono } from 'hono';
import { ChiefInformationSecurityOfficer } from './agents/chief-information-security-officer.ts';
import { SecurityEngineer } from './agents/security-engineer.ts';
import { ApplicationSecurityEngineer } from './agents/application-security-engineer.ts';
import { PenetrationTester } from './agents/penetration-tester.ts';
import { SecurityAnalyst } from './agents/security-analyst.ts';
import { ComplianceOfficer } from './agents/compliance-officer.ts';
import { IdentityAccessManager } from './agents/identity-access-manager.ts';
import { SecurityOperationsAnalyst } from './agents/security-operations-analyst.ts';

// Every model call goes through this department's own AI Gateway (budgets, logs, rate limits).
setProvider(
  cloudflareBindingProvider({
    binding: env.AI,
    gateway: { id: "dept-security-compliance", metadata: { department: "security-compliance" } },
  }),
);

const app = new Hono();
app.get('/healthz', (c) => c.text('ok'));
app.use('/agents/*', requireCaller());
app.route('/agents/chief-information-security-officer', createAgentRouter(ChiefInformationSecurityOfficer));
app.route('/agents/security-engineer', createAgentRouter(SecurityEngineer));
app.route('/agents/application-security-engineer', createAgentRouter(ApplicationSecurityEngineer));
app.route('/agents/penetration-tester', createAgentRouter(PenetrationTester));
app.route('/agents/security-analyst', createAgentRouter(SecurityAnalyst));
app.route('/agents/compliance-officer', createAgentRouter(ComplianceOfficer));
app.route('/agents/identity-access-manager', createAgentRouter(IdentityAccessManager));
app.route('/agents/security-operations-analyst', createAgentRouter(SecurityOperationsAnalyst));

export default app;
