// GENERATED by scripts/generate.mjs from the role manifest. Do not edit; edit roles/<slug>.json instead.
'use agent';
import { useRole } from '@org/harness';
import type { RoleManifest } from '@org/harness';
import manifest from '../../roles/chief-information-security-officer.json';
import skill_security_compliance_playbook from '../skills/security-compliance-playbook/SKILL.md';
import skill_org_conventions from '../skills/org-conventions/SKILL.md';
import { SecurityEngineer } from './security-engineer.ts';
import { ApplicationSecurityEngineer } from './application-security-engineer.ts';
import { PenetrationTester } from './penetration-tester.ts';
import { SecurityAnalyst } from './security-analyst.ts';
import { ComplianceOfficer } from './compliance-officer.ts';
import { IdentityAccessManager } from './identity-access-manager.ts';
import { SecurityOperationsAnalyst } from './security-operations-analyst.ts';

export function ChiefInformationSecurityOfficer() {
  return useRole(
    { manifest: { ...manifest, mcp: [{"id":"github","tier":"read"},{"id":"cloudflare","tier":"read"}] } as RoleManifest, skills: [skill_security_compliance_playbook, skill_org_conventions] },
    { team: {
      'security-engineer': { agent: SecurityEngineer, name: "Security Engineer" },
      'application-security-engineer': { agent: ApplicationSecurityEngineer, name: "Application Security Engineer" },
      'penetration-tester': { agent: PenetrationTester, name: "Penetration Tester" },
      'security-analyst': { agent: SecurityAnalyst, name: "Security Analyst" },
      'compliance-officer': { agent: ComplianceOfficer, name: "Compliance Officer" },
      'identity-access-manager': { agent: IdentityAccessManager, name: "Identity & Access Manager" },
      'security-operations-analyst': { agent: SecurityOperationsAnalyst, name: "Security Operations Analyst" },
    } },
  );
}
