// GENERATED by scripts/generate.mjs from the role manifest. Do not edit; edit roles/<slug>.json instead.
'use agent';
import { useRole } from '@org/harness';
import type { RoleManifest } from '@org/harness';
import manifest from '../../roles/security-operations-analyst.json';
import skill_security_compliance_playbook from '../skills/security-compliance-playbook/SKILL.md';
import skill_org_conventions from '../skills/org-conventions/SKILL.md';

export function SecurityOperationsAnalyst() {
  return useRole(
    { manifest: manifest as RoleManifest, skills: [skill_security_compliance_playbook, skill_org_conventions] },
  );
}
