// GENERATED by scripts/generate.mjs from the role manifest. Do not edit; edit roles/<slug>.json instead.
'use agent';
import { useRole } from '@org/harness';
import type { RoleManifest } from '@org/harness';
import manifest from '../../roles/frontend-lead-principal.json';
import skill_frontend_development_playbook from '../skills/frontend-development-playbook/SKILL.md';
import skill_org_conventions from '../skills/org-conventions/SKILL.md';
import { FrontendDeveloper } from './frontend-developer.ts';
import { JavascriptTypescriptDeveloper } from './javascript-typescript-developer.ts';
import { CssStylingSpecialist } from './css-styling-specialist.ts';
import { FrontendPerformanceEngineer } from './frontend-performance-engineer.ts';
import { WebAccessibilityDeveloper } from './web-accessibility-developer.ts';
import { FrontendBuildEngineer } from './frontend-build-engineer.ts';

export function FrontendLeadPrincipal() {
  return useRole(
    { manifest: manifest as RoleManifest, skills: [skill_frontend_development_playbook, skill_org_conventions] },
    { team: {
      'frontend-developer': { agent: FrontendDeveloper, name: "Frontend Developer" },
      'javascript-typescript-developer': { agent: JavascriptTypescriptDeveloper, name: "JavaScript/TypeScript Developer" },
      'css-styling-specialist': { agent: CssStylingSpecialist, name: "CSS/Styling Specialist" },
      'frontend-performance-engineer': { agent: FrontendPerformanceEngineer, name: "Frontend Performance Engineer" },
      'web-accessibility-developer': { agent: WebAccessibilityDeveloper, name: "Web Accessibility Developer" },
      'frontend-build-engineer': { agent: FrontendBuildEngineer, name: "Frontend Build Engineer" },
    } },
  );
}
