// GENERATED by scripts/generate.mjs from the role manifest. Do not edit; edit roles/<slug>.json instead.
'use agent';
import { useRole } from '@org/harness';
import type { RoleManifest } from '@org/harness';
import manifest from '../../roles/javascript-typescript-developer.json';
import skill_frontend_development_playbook from '../skills/frontend-development-playbook/SKILL.md';
import skill_org_conventions from '../skills/org-conventions/SKILL.md';

export function JavascriptTypescriptDeveloper() {
  return useRole(
    { manifest: { ...manifest, mcp: [{"id":"github","tier":"read"},{"id":"cloudflare","tier":"read"}] } as RoleManifest, skills: [skill_frontend_development_playbook, skill_org_conventions] },
  );
}
