// GENERATED by scripts/generate.mjs. Do not edit.
import { setProvider } from '@flue/runtime';
import { cloudflareBindingProvider } from '@flue/runtime/cloudflare/workers-ai';
import { createAgentRouter } from '@flue/runtime/routing';
import { requireCaller } from '@org/harness';
import { env } from 'cloudflare:workers';
import { Hono } from 'hono';
import { ProgramManager } from './agents/program-manager.ts';
import { ProjectManager } from './agents/project-manager.ts';
import { TechnicalProjectManager } from './agents/technical-project-manager.ts';
import { DeliveryManager } from './agents/delivery-manager.ts';
import { ResourceManager } from './agents/resource-manager.ts';
import { PmoAnalyst } from './agents/pmo-analyst.ts';
import { PortfolioManager } from './agents/portfolio-manager.ts';

// Every model call goes through this department's own AI Gateway (budgets, logs, rate limits).
setProvider(
  cloudflareBindingProvider({
    binding: env.AI,
    gateway: { id: "dept-project-management", metadata: { department: "project-management" } },
  }),
);

const app = new Hono();
app.get('/healthz', (c) => c.text('ok'));
app.use('/agents/*', requireCaller());
app.route('/agents/program-manager', createAgentRouter(ProgramManager));
app.route('/agents/project-manager', createAgentRouter(ProjectManager));
app.route('/agents/technical-project-manager', createAgentRouter(TechnicalProjectManager));
app.route('/agents/delivery-manager', createAgentRouter(DeliveryManager));
app.route('/agents/resource-manager', createAgentRouter(ResourceManager));
app.route('/agents/pmo-analyst', createAgentRouter(PmoAnalyst));
app.route('/agents/portfolio-manager', createAgentRouter(PortfolioManager));

export default app;
