// GENERATED by scripts/generate.mjs. Do not edit.
import { setProvider } from '@flue/runtime';
import { cloudflareBindingProvider } from '@flue/runtime/cloudflare/workers-ai';
import { createAgentRouter } from '@flue/runtime/routing';
import { requireCaller } from '@org/harness';
import { env } from 'cloudflare:workers';
import { Hono } from 'hono';
import { DataEngineeringManager } from './agents/data-engineering-manager.ts';
import { DataEngineer } from './agents/data-engineer.ts';
import { DataWarehouseEngineer } from './agents/data-warehouse-engineer.ts';
import { EtlDeveloper } from './agents/etl-developer.ts';
import { DataAnalyst } from './agents/data-analyst.ts';
import { BusinessIntelligenceDeveloper } from './agents/business-intelligence-developer.ts';
import { DataScientist } from './agents/data-scientist.ts';
import { MlEngineer } from './agents/ml-engineer.ts';
import { AnalyticsEngineer } from './agents/analytics-engineer.ts';

// Every model call goes through this department's own AI Gateway (budgets, logs, rate limits).
setProvider(
  cloudflareBindingProvider({
    binding: env.AI,
    gateway: { id: "dept-data-engineering-analytics", metadata: { department: "data-engineering-analytics" } },
  }),
);

const app = new Hono();
app.get('/healthz', (c) => c.text('ok'));
app.use('/agents/*', requireCaller());
app.route('/agents/data-engineering-manager', createAgentRouter(DataEngineeringManager));
app.route('/agents/data-engineer', createAgentRouter(DataEngineer));
app.route('/agents/data-warehouse-engineer', createAgentRouter(DataWarehouseEngineer));
app.route('/agents/etl-developer', createAgentRouter(EtlDeveloper));
app.route('/agents/data-analyst', createAgentRouter(DataAnalyst));
app.route('/agents/business-intelligence-developer', createAgentRouter(BusinessIntelligenceDeveloper));
app.route('/agents/data-scientist', createAgentRouter(DataScientist));
app.route('/agents/ml-engineer', createAgentRouter(MlEngineer));
app.route('/agents/analytics-engineer', createAgentRouter(AnalyticsEngineer));

export default app;
