// GENERATED by scripts/generate.mjs from the role manifest. Do not edit; edit roles/<slug>.json instead.
'use agent';
import { useRole } from '@org/harness';
import type { RoleManifest } from '@org/harness';
import manifest from '../../roles/design-director.json';
import skill_design_playbook from '../skills/design-playbook/SKILL.md';
import skill_org_conventions from '../skills/org-conventions/SKILL.md';
import { UxDesigner } from './ux-designer.ts';
import { UiDesigner } from './ui-designer.ts';
import { InteractionDesigner } from './interaction-designer.ts';
import { VisualDesigner } from './visual-designer.ts';
import { MotionDesigner } from './motion-designer.ts';
import { DesignSystemManager } from './design-system-manager.ts';
import { Prototyper } from './prototyper.ts';

export function DesignDirector() {
  return useRole(
    { manifest: manifest as RoleManifest, skills: [skill_design_playbook, skill_org_conventions] },
    { team: {
      'ux-designer': { agent: UxDesigner, name: "UX Designer" },
      'ui-designer': { agent: UiDesigner, name: "UI Designer" },
      'interaction-designer': { agent: InteractionDesigner, name: "Interaction Designer" },
      'visual-designer': { agent: VisualDesigner, name: "Visual Designer" },
      'motion-designer': { agent: MotionDesigner, name: "Motion Designer" },
      'design-system-manager': { agent: DesignSystemManager, name: "Design System Manager" },
      'prototyper': { agent: Prototyper, name: "Prototyper" },
    } },
  );
}
