// GENERATED by scripts/generate.mjs from the role manifest. Do not edit; edit roles/<slug>.json instead.
'use agent';
import { useRole } from '@org/harness';
import type { RoleManifest } from '@org/harness';
import manifest from '../../roles/prototyper.json';
import skill_design_playbook from '../skills/design-playbook/SKILL.md';
import skill_org_conventions from '../skills/org-conventions/SKILL.md';

export function Prototyper() {
  return useRole(
    { manifest: manifest as RoleManifest, skills: [skill_design_playbook, skill_org_conventions] },
  );
}
