// GENERATED by scripts/generate.mjs. Do not edit.
import { setProvider } from '@flue/runtime';
import { cloudflareBindingProvider } from '@flue/runtime/cloudflare/workers-ai';
import { createAgentRouter } from '@flue/runtime/routing';
import { requireCaller } from '@org/harness';
import { env } from 'cloudflare:workers';
import { Hono } from 'hono';
import { UxResearchLead } from './agents/ux-research-lead.ts';
import { UserResearcher } from './agents/user-researcher.ts';
import { BehavioralAnalyst } from './agents/behavioral-analyst.ts';
import { AccessibilitySpecialist } from './agents/accessibility-specialist.ts';
import { InformationArchitect } from './agents/information-architect.ts';
import { UsabilityTester } from './agents/usability-tester.ts';

// Every model call goes through this department's own AI Gateway (budgets, logs, rate limits).
setProvider(
  cloudflareBindingProvider({
    binding: env.AI,
    gateway: { id: "dept-user-research-experience", metadata: { department: "user-research-experience" } },
  }),
);

const app = new Hono();
app.get('/healthz', (c) => c.text('ok'));
app.use('/agents/*', requireCaller());
app.route('/agents/ux-research-lead', createAgentRouter(UxResearchLead));
app.route('/agents/user-researcher', createAgentRouter(UserResearcher));
app.route('/agents/behavioral-analyst', createAgentRouter(BehavioralAnalyst));
app.route('/agents/accessibility-specialist', createAgentRouter(AccessibilitySpecialist));
app.route('/agents/information-architect', createAgentRouter(InformationArchitect));
app.route('/agents/usability-tester', createAgentRouter(UsabilityTester));

export default app;
