// GENERATED by scripts/generate.mjs from the role manifest. Do not edit; edit roles/<slug>.json instead.
'use agent';
import { useRole } from '@org/harness';
import type { RoleManifest } from '@org/harness';
import manifest from '../../roles/lead-business-analyst.json';
import skill_business_analysis_requirements_playbook from '../skills/business-analysis-requirements-playbook/SKILL.md';
import skill_org_conventions from '../skills/org-conventions/SKILL.md';
import { BusinessAnalyst } from './business-analyst.ts';
import { SystemsAnalyst } from './systems-analyst.ts';
import { ProcessAnalyst } from './process-analyst.ts';
import { DomainExpertSme } from './domain-expert-sme.ts';
import { RequirementsEngineer } from './requirements-engineer.ts';

export function LeadBusinessAnalyst() {
  return useRole(
    { manifest: { ...manifest, mcp: [] } as RoleManifest, skills: [skill_business_analysis_requirements_playbook, skill_org_conventions] },
    { team: {
      'business-analyst': { agent: BusinessAnalyst, name: "Business Analyst" },
      'systems-analyst': { agent: SystemsAnalyst, name: "Systems Analyst" },
      'process-analyst': { agent: ProcessAnalyst, name: "Process Analyst" },
      'domain-expert-sme': { agent: DomainExpertSme, name: "Domain Expert/SME" },
      'requirements-engineer': { agent: RequirementsEngineer, name: "Requirements Engineer" },
    } },
  );
}
