// GENERATED by scripts/generate.mjs from the role manifest. Do not edit; edit roles/<slug>.json instead.
'use agent';
import { useRole } from '@org/harness';
import type { RoleManifest } from '@org/harness';
import manifest from '../../roles/process-analyst.json';
import skill_business_analysis_requirements_playbook from '../skills/business-analysis-requirements-playbook/SKILL.md';
import skill_org_conventions from '../skills/org-conventions/SKILL.md';

export function ProcessAnalyst() {
  return useRole(
    { manifest: manifest as RoleManifest, skills: [skill_business_analysis_requirements_playbook, skill_org_conventions] },
  );
}
