// GENERATED by scripts/generate.mjs. Do not edit.
import { setProvider } from '@flue/runtime';
import { cloudflareBindingProvider } from '@flue/runtime/cloudflare/workers-ai';
import { createAgentRouter } from '@flue/runtime/routing';
import { requireCaller } from '@org/harness';
import { env } from 'cloudflare:workers';
import { Hono } from 'hono';
import { LeadBusinessAnalyst } from './agents/lead-business-analyst.ts';
import { BusinessAnalyst } from './agents/business-analyst.ts';
import { SystemsAnalyst } from './agents/systems-analyst.ts';
import { ProcessAnalyst } from './agents/process-analyst.ts';
import { DomainExpertSme } from './agents/domain-expert-sme.ts';
import { RequirementsEngineer } from './agents/requirements-engineer.ts';

// Every model call goes through this department's own AI Gateway (budgets, logs, rate limits).
setProvider(
  cloudflareBindingProvider({
    binding: env.AI,
    gateway: { id: "dept-business-analysis-requirements", metadata: { department: "business-analysis-requirements" } },
  }),
);

const app = new Hono();
app.get('/healthz', (c) => c.text('ok'));
app.use('/agents/*', requireCaller());
app.route('/agents/lead-business-analyst', createAgentRouter(LeadBusinessAnalyst));
app.route('/agents/business-analyst', createAgentRouter(BusinessAnalyst));
app.route('/agents/systems-analyst', createAgentRouter(SystemsAnalyst));
app.route('/agents/process-analyst', createAgentRouter(ProcessAnalyst));
app.route('/agents/domain-expert-sme', createAgentRouter(DomainExpertSme));
app.route('/agents/requirements-engineer', createAgentRouter(RequirementsEngineer));

export default app;
