// GENERATED by scripts/generate.mjs. Do not edit.
import { setProvider } from '@flue/runtime';
import { cloudflareBindingProvider } from '@flue/runtime/cloudflare/workers-ai';
import { createAgentRouter } from '@flue/runtime/routing';
import { requireCaller } from '@org/harness';
import { env } from 'cloudflare:workers';
import { Hono } from 'hono';
import { GeneralCounsel } from './agents/general-counsel.ts';
import { CorporateLawyer } from './agents/corporate-lawyer.ts';
import { PrivacyOfficer } from './agents/privacy-officer.ts';
import { IntellectualPropertyAttorney } from './agents/intellectual-property-attorney.ts';
import { ComplianceManager } from './agents/compliance-manager.ts';
import { ContractManager } from './agents/contract-manager.ts';
import { Paralegal } from './agents/paralegal.ts';

// Every model call goes through this department's own AI Gateway (budgets, logs, rate limits).
setProvider(
  cloudflareBindingProvider({
    binding: env.AI,
    gateway: { id: "dept-legal-compliance", metadata: { department: "legal-compliance" } },
  }),
);

const app = new Hono();
app.get('/healthz', (c) => c.text('ok'));
app.use('/agents/*', requireCaller());
app.route('/agents/general-counsel', createAgentRouter(GeneralCounsel));
app.route('/agents/corporate-lawyer', createAgentRouter(CorporateLawyer));
app.route('/agents/privacy-officer', createAgentRouter(PrivacyOfficer));
app.route('/agents/intellectual-property-attorney', createAgentRouter(IntellectualPropertyAttorney));
app.route('/agents/compliance-manager', createAgentRouter(ComplianceManager));
app.route('/agents/contract-manager', createAgentRouter(ContractManager));
app.route('/agents/paralegal', createAgentRouter(Paralegal));

export default app;
