// GENERATED by scripts/generate.mjs from the role manifest. Do not edit; edit roles/<slug>.json instead.
'use agent';
import { useRole } from '@org/harness';
import type { RoleManifest } from '@org/harness';
import manifest from '../../roles/head-of-support.json';
import skill_customer_support_playbook from '../skills/customer-support-playbook/SKILL.md';
import skill_org_conventions from '../skills/org-conventions/SKILL.md';
import { CustomerSupportRepTier1 } from './customer-support-rep-tier-1.ts';
import { TechnicalSupportEngineerTier2 } from './technical-support-engineer-tier-2.ts';
import { SeniorSupportEngineerTier3 } from './senior-support-engineer-tier-3.ts';
import { SupportOperationsManager } from './support-operations-manager.ts';
import { CommunityManager } from './community-manager.ts';
import { CustomerAdvocate } from './customer-advocate.ts';
import { OnboardingSpecialist } from './onboarding-specialist.ts';
import { TrainingSpecialist } from './training-specialist.ts';

export function HeadOfSupport() {
  return useRole(
    { manifest: { ...manifest, mcp: [] } as RoleManifest, skills: [skill_customer_support_playbook, skill_org_conventions] },
    { team: {
      'customer-support-rep-tier-1': { agent: CustomerSupportRepTier1, name: "Customer Support Rep (Tier 1)" },
      'technical-support-engineer-tier-2': { agent: TechnicalSupportEngineerTier2, name: "Technical Support Engineer (Tier 2)" },
      'senior-support-engineer-tier-3': { agent: SeniorSupportEngineerTier3, name: "Senior Support Engineer (Tier 3)" },
      'support-operations-manager': { agent: SupportOperationsManager, name: "Support Operations Manager" },
      'community-manager': { agent: CommunityManager, name: "Community Manager" },
      'customer-advocate': { agent: CustomerAdvocate, name: "Customer Advocate" },
      'onboarding-specialist': { agent: OnboardingSpecialist, name: "Onboarding Specialist" },
      'training-specialist': { agent: TrainingSpecialist, name: "Training Specialist" },
    } },
  );
}
