// GENERATED by scripts/generate.mjs from the role manifest. Do not edit; edit roles/<slug>.json instead.
'use agent';
import { useRole } from '@org/harness';
import type { RoleManifest } from '@org/harness';
import manifest from '../../roles/technical-support-engineer-tier-2.json';
import skill_customer_support_playbook from '../skills/customer-support-playbook/SKILL.md';
import skill_org_conventions from '../skills/org-conventions/SKILL.md';

export function TechnicalSupportEngineerTier2() {
  return useRole(
    { manifest: { ...manifest, mcp: [] } as RoleManifest, skills: [skill_customer_support_playbook, skill_org_conventions] },
  );
}
