// GENERATED by scripts/generate.mjs. Do not edit.
import { setProvider } from '@flue/runtime';
import { cloudflareBindingProvider } from '@flue/runtime/cloudflare/workers-ai';
import { createAgentRouter } from '@flue/runtime/routing';
import { requireCaller } from '@org/harness';
import { env } from 'cloudflare:workers';
import { Hono } from 'hono';
import { BackendLeadPrincipal } from './agents/backend-lead-principal.ts';
import { BackendDeveloper } from './agents/backend-developer.ts';
import { ApiDeveloper } from './agents/api-developer.ts';
import { DatabaseDeveloper } from './agents/database-developer.ts';
import { MicroservicesDeveloper } from './agents/microservices-developer.ts';
import { BackendPerformanceEngineer } from './agents/backend-performance-engineer.ts';
import { IntegrationDeveloper } from './agents/integration-developer.ts';

// Every model call goes through this department's own AI Gateway (budgets, logs, rate limits).
setProvider(
  cloudflareBindingProvider({
    binding: env.AI,
    gateway: { id: "dept-backend-development", metadata: { department: "backend-development" } },
  }),
);

const app = new Hono();
app.get('/healthz', (c) => c.text('ok'));
app.use('/agents/*', requireCaller());
app.route('/agents/backend-lead-principal', createAgentRouter(BackendLeadPrincipal));
app.route('/agents/backend-developer', createAgentRouter(BackendDeveloper));
app.route('/agents/api-developer', createAgentRouter(ApiDeveloper));
app.route('/agents/database-developer', createAgentRouter(DatabaseDeveloper));
app.route('/agents/microservices-developer', createAgentRouter(MicroservicesDeveloper));
app.route('/agents/backend-performance-engineer', createAgentRouter(BackendPerformanceEngineer));
app.route('/agents/integration-developer', createAgentRouter(IntegrationDeveloper));

export default app;
