// GENERATED by scripts/generate.mjs. Do not edit.
import { setProvider } from '@flue/runtime';
import { cloudflareBindingProvider } from '@flue/runtime/cloudflare/workers-ai';
import { createAgentRouter } from '@flue/runtime/routing';
import { requireCaller } from '@org/harness';
import { env } from 'cloudflare:workers';
import { Hono } from 'hono';
import { ChiefArchitect } from './agents/chief-architect.ts';
import { SolutionsArchitect } from './agents/solutions-architect.ts';
import { ApplicationArchitect } from './agents/application-architect.ts';
import { DataArchitect } from './agents/data-architect.ts';
import { CloudArchitect } from './agents/cloud-architect.ts';
import { IntegrationArchitect } from './agents/integration-architect.ts';
import { SecurityArchitect } from './agents/security-architect.ts';

// Every model call goes through this department's own AI Gateway (budgets, logs, rate limits).
setProvider(
  cloudflareBindingProvider({
    binding: env.AI,
    gateway: { id: "dept-software-architecture", metadata: { department: "software-architecture" } },
  }),
);

const app = new Hono();
app.get('/healthz', (c) => c.text('ok'));
app.use('/agents/*', requireCaller());
app.route('/agents/chief-architect', createAgentRouter(ChiefArchitect));
app.route('/agents/solutions-architect', createAgentRouter(SolutionsArchitect));
app.route('/agents/application-architect', createAgentRouter(ApplicationArchitect));
app.route('/agents/data-architect', createAgentRouter(DataArchitect));
app.route('/agents/cloud-architect', createAgentRouter(CloudArchitect));
app.route('/agents/integration-architect', createAgentRouter(IntegrationArchitect));
app.route('/agents/security-architect', createAgentRouter(SecurityArchitect));

export default app;
