// GENERATED by scripts/generate.mjs from the role manifest. Do not edit; edit roles/<slug>.json instead.
'use agent';
import { useRole } from '@org/harness';
import type { RoleManifest } from '@org/harness';
import manifest from '../../roles/mobile-lead.json';
import skill_mobile_development_playbook from '../skills/mobile-development-playbook/SKILL.md';
import skill_org_conventions from '../skills/org-conventions/SKILL.md';
import { IosDeveloper } from './ios-developer.ts';
import { AndroidDeveloper } from './android-developer.ts';
import { ReactNativeDeveloper } from './react-native-developer.ts';
import { FlutterDeveloper } from './flutter-developer.ts';
import { MobileUiUxDeveloper } from './mobile-ui-ux-developer.ts';
import { MobileDevopsEngineer } from './mobile-devops-engineer.ts';

export function MobileLead() {
  return useRole(
    { manifest: manifest as RoleManifest, skills: [skill_mobile_development_playbook, skill_org_conventions] },
    { team: {
      'ios-developer': { agent: IosDeveloper, name: "iOS Developer" },
      'android-developer': { agent: AndroidDeveloper, name: "Android Developer" },
      'react-native-developer': { agent: ReactNativeDeveloper, name: "React Native Developer" },
      'flutter-developer': { agent: FlutterDeveloper, name: "Flutter Developer" },
      'mobile-ui-ux-developer': { agent: MobileUiUxDeveloper, name: "Mobile UI/UX Developer" },
      'mobile-devops-engineer': { agent: MobileDevopsEngineer, name: "Mobile DevOps Engineer" },
    } },
  );
}
