// GENERATED by scripts/generate.mjs from the role manifest. Do not edit; edit roles/<slug>.json instead.
'use agent';
import { useRole } from '@org/harness';
import type { RoleManifest } from '@org/harness';
import manifest from '../../roles/documentation-manager.json';
import skill_documentation_technical_writing_playbook from '../skills/documentation-technical-writing-playbook/SKILL.md';
import skill_org_conventions from '../skills/org-conventions/SKILL.md';
import { TechnicalWriter } from './technical-writer.ts';
import { ApiDocumentationSpecialist } from './api-documentation-specialist.ts';
import { KnowledgeBaseManager } from './knowledge-base-manager.ts';
import { VideoTutorialCreator } from './video-tutorial-creator.ts';
import { InformationDeveloper } from './information-developer.ts';
import { ContentStrategist } from './content-strategist.ts';

export function DocumentationManager() {
  return useRole(
    { manifest: { ...manifest, mcp: [{"id":"github","tier":"write"}] } as RoleManifest, skills: [skill_documentation_technical_writing_playbook, skill_org_conventions] },
    { team: {
      'technical-writer': { agent: TechnicalWriter, name: "Technical Writer" },
      'api-documentation-specialist': { agent: ApiDocumentationSpecialist, name: "API Documentation Specialist" },
      'knowledge-base-manager': { agent: KnowledgeBaseManager, name: "Knowledge Base Manager" },
      'video-tutorial-creator': { agent: VideoTutorialCreator, name: "Video Tutorial Creator" },
      'information-developer': { agent: InformationDeveloper, name: "Information Developer" },
      'content-strategist': { agent: ContentStrategist, name: "Content Strategist" },
    } },
  );
}
