// GENERATED by scripts/generate.mjs from the role manifest. Do not edit; edit roles/<slug>.json instead.
'use agent';
import { useRole } from '@org/harness';
import type { RoleManifest } from '@org/harness';
import manifest from '../../roles/technical-writer.json';
import skill_documentation_technical_writing_playbook from '../skills/documentation-technical-writing-playbook/SKILL.md';
import skill_org_conventions from '../skills/org-conventions/SKILL.md';

export function TechnicalWriter() {
  return useRole(
    { manifest: { ...manifest, mcp: [{"id":"github","tier":"read"}] } as RoleManifest, skills: [skill_documentation_technical_writing_playbook, skill_org_conventions] },
  );
}
