// GENERATED by scripts/generate.mjs from the role manifest. Do not edit; edit roles/<slug>.json instead.
'use agent';
import { useRole } from '@org/harness';
import type { RoleManifest } from '@org/harness';
import manifest from '../../roles/full-stack-lead.json';
import skill_full_stack_development_playbook from '../skills/full-stack-development-playbook/SKILL.md';
import skill_org_conventions from '../skills/org-conventions/SKILL.md';
import { FullStackDeveloper } from './full-stack-developer.ts';
import { MeanMernStackDeveloper } from './mean-mern-stack-developer.ts';
import { RapidPrototyper } from './rapid-prototyper.ts';

export function FullStackLead() {
  return useRole(
    { manifest: { ...manifest, mcp: [{"id":"github","tier":"write"},{"id":"cloudflare","tier":"read"}] } as RoleManifest, skills: [skill_full_stack_development_playbook, skill_org_conventions] },
    { team: {
      'full-stack-developer': { agent: FullStackDeveloper, name: "Full Stack Developer" },
      'mean-mern-stack-developer': { agent: MeanMernStackDeveloper, name: "MEAN/MERN Stack Developer" },
      'rapid-prototyper': { agent: RapidPrototyper, name: "Rapid Prototyper" },
    } },
  );
}
