// GENERATED by scripts/generate.mjs from the role manifest. Do not edit; edit roles/<slug>.json instead.
'use agent';
import { useRole } from '@org/harness';
import type { RoleManifest } from '@org/harness';
import manifest from '../../roles/full-stack-developer.json';
import skill_full_stack_development_playbook from '../skills/full-stack-development-playbook/SKILL.md';
import skill_org_conventions from '../skills/org-conventions/SKILL.md';

export function FullStackDeveloper() {
  return useRole(
    { manifest: manifest as RoleManifest, skills: [skill_full_stack_development_playbook, skill_org_conventions] },
  );
}
