// GENERATED by scripts/generate.mjs. Do not edit.
import { setProvider } from '@flue/runtime';
import { cloudflareBindingProvider } from '@flue/runtime/cloudflare/workers-ai';
import { createAgentRouter } from '@flue/runtime/routing';
import { requireCaller } from '@org/harness';
import { env } from 'cloudflare:workers';
import { Hono } from 'hono';
import { FrontendLeadPrincipal } from './agents/frontend-lead-principal.ts';
import { FrontendDeveloper } from './agents/frontend-developer.ts';
import { JavascriptTypescriptDeveloper } from './agents/javascript-typescript-developer.ts';
import { CssStylingSpecialist } from './agents/css-styling-specialist.ts';
import { FrontendPerformanceEngineer } from './agents/frontend-performance-engineer.ts';
import { WebAccessibilityDeveloper } from './agents/web-accessibility-developer.ts';
import { FrontendBuildEngineer } from './agents/frontend-build-engineer.ts';

// Every model call goes through this department's own AI Gateway (budgets, logs, rate limits).
setProvider(
  cloudflareBindingProvider({
    binding: env.AI,
    gateway: { id: "dept-frontend-development", metadata: { department: "frontend-development" } },
  }),
);

const app = new Hono();
app.get('/healthz', (c) => c.text('ok'));
app.use('/agents/*', requireCaller());
app.route('/agents/frontend-lead-principal', createAgentRouter(FrontendLeadPrincipal));
app.route('/agents/frontend-developer', createAgentRouter(FrontendDeveloper));
app.route('/agents/javascript-typescript-developer', createAgentRouter(JavascriptTypescriptDeveloper));
app.route('/agents/css-styling-specialist', createAgentRouter(CssStylingSpecialist));
app.route('/agents/frontend-performance-engineer', createAgentRouter(FrontendPerformanceEngineer));
app.route('/agents/web-accessibility-developer', createAgentRouter(WebAccessibilityDeveloper));
app.route('/agents/frontend-build-engineer', createAgentRouter(FrontendBuildEngineer));

export default app;
