// GENERATED by scripts/generate.mjs from the role manifest. Do not edit; edit roles/<slug>.json instead.
'use agent';
import { useRole } from '@org/harness';
import type { RoleManifest } from '@org/harness';
import manifest from '../../roles/devops-manager.json';
import skill_devops_infrastructure_playbook from '../skills/devops-infrastructure-playbook/SKILL.md';
import skill_org_conventions from '../skills/org-conventions/SKILL.md';
import { DevopsEngineer } from './devops-engineer.ts';
import { SiteReliabilityEngineerSre } from './site-reliability-engineer-sre.ts';
import { CloudEngineer } from './cloud-engineer.ts';
import { PlatformEngineer } from './platform-engineer.ts';
import { ReleaseManager } from './release-manager.ts';
import { InfrastructureEngineer } from './infrastructure-engineer.ts';
import { CiCdEngineer } from './ci-cd-engineer.ts';
import { ConfigurationManager } from './configuration-manager.ts';
import { MonitoringObservabilityEngineer } from './monitoring-observability-engineer.ts';

export function DevopsManager() {
  return useRole(
    { manifest: manifest as RoleManifest, skills: [skill_devops_infrastructure_playbook, skill_org_conventions] },
    { team: {
      'devops-engineer': { agent: DevopsEngineer, name: "DevOps Engineer" },
      'site-reliability-engineer-sre': { agent: SiteReliabilityEngineerSre, name: "Site Reliability Engineer (SRE)" },
      'cloud-engineer': { agent: CloudEngineer, name: "Cloud Engineer" },
      'platform-engineer': { agent: PlatformEngineer, name: "Platform Engineer" },
      'release-manager': { agent: ReleaseManager, name: "Release Manager" },
      'infrastructure-engineer': { agent: InfrastructureEngineer, name: "Infrastructure Engineer" },
      'ci-cd-engineer': { agent: CiCdEngineer, name: "CI/CD Engineer" },
      'configuration-manager': { agent: ConfigurationManager, name: "Configuration Manager" },
      'monitoring-observability-engineer': { agent: MonitoringObservabilityEngineer, name: "Monitoring/Observability Engineer" },
    } },
  );
}
