// GENERATED by scripts/generate.mjs. Do not edit.
import { setProvider } from '@flue/runtime';
import { cloudflareBindingProvider } from '@flue/runtime/cloudflare/workers-ai';
import { createAgentRouter } from '@flue/runtime/routing';
import { requireCaller } from '@org/harness';
import { env } from 'cloudflare:workers';
import { Hono } from 'hono';
import { DesignDirector } from './agents/design-director.ts';
import { UxDesigner } from './agents/ux-designer.ts';
import { UiDesigner } from './agents/ui-designer.ts';
import { InteractionDesigner } from './agents/interaction-designer.ts';
import { VisualDesigner } from './agents/visual-designer.ts';
import { MotionDesigner } from './agents/motion-designer.ts';
import { DesignSystemManager } from './agents/design-system-manager.ts';
import { Prototyper } from './agents/prototyper.ts';

// Every model call goes through this department's own AI Gateway (budgets, logs, rate limits).
setProvider(
  cloudflareBindingProvider({
    binding: env.AI,
    gateway: { id: "dept-design", metadata: { department: "design" } },
  }),
);

const app = new Hono();
app.get('/healthz', (c) => c.text('ok'));
app.use('/agents/*', requireCaller());
app.route('/agents/design-director', createAgentRouter(DesignDirector));
app.route('/agents/ux-designer', createAgentRouter(UxDesigner));
app.route('/agents/ui-designer', createAgentRouter(UiDesigner));
app.route('/agents/interaction-designer', createAgentRouter(InteractionDesigner));
app.route('/agents/visual-designer', createAgentRouter(VisualDesigner));
app.route('/agents/motion-designer', createAgentRouter(MotionDesigner));
app.route('/agents/design-system-manager', createAgentRouter(DesignSystemManager));
app.route('/agents/prototyper', createAgentRouter(Prototyper));

export default app;
