// GENERATED by scripts/generate.mjs from the role manifest. Do not edit; edit roles/<slug>.json instead.
'use agent';
import { useRole } from '@org/harness';
import type { RoleManifest } from '@org/harness';
import manifest from '../../roles/backend-lead-principal.json';
import skill_backend_development_playbook from '../skills/backend-development-playbook/SKILL.md';
import skill_org_conventions from '../skills/org-conventions/SKILL.md';
import { BackendDeveloper } from './backend-developer.ts';
import { ApiDeveloper } from './api-developer.ts';
import { DatabaseDeveloper } from './database-developer.ts';
import { MicroservicesDeveloper } from './microservices-developer.ts';
import { BackendPerformanceEngineer } from './backend-performance-engineer.ts';
import { IntegrationDeveloper } from './integration-developer.ts';

export function BackendLeadPrincipal() {
  return useRole(
    { manifest: { ...manifest, mcp: [{"id":"github","tier":"write"},{"id":"cloudflare","tier":"read"}] } as RoleManifest, skills: [skill_backend_development_playbook, skill_org_conventions] },
    { team: {
      'backend-developer': { agent: BackendDeveloper, name: "Backend Developer" },
      'api-developer': { agent: ApiDeveloper, name: "API Developer" },
      'database-developer': { agent: DatabaseDeveloper, name: "Database Developer" },
      'microservices-developer': { agent: MicroservicesDeveloper, name: "Microservices Developer" },
      'backend-performance-engineer': { agent: BackendPerformanceEngineer, name: "Backend Performance Engineer" },
      'integration-developer': { agent: IntegrationDeveloper, name: "Integration Developer" },
    } },
  );
}
