// GENERATED by scripts/generate.mjs from the role manifest. Do not edit; edit roles/<slug>.json instead.
'use agent';
import { useRole } from '@org/harness';
import type { RoleManifest } from '@org/harness';
import manifest from '../../roles/microservices-developer.json';
import skill_backend_development_playbook from '../skills/backend-development-playbook/SKILL.md';
import skill_org_conventions from '../skills/org-conventions/SKILL.md';

export function MicroservicesDeveloper() {
  return useRole(
    { manifest: manifest as RoleManifest, skills: [skill_backend_development_playbook, skill_org_conventions] },
  );
}
