#!/usr/bin/env node
// Generates everything derivable from departments/*/{policy.json,roles/*.json}.
//   node scripts/generate.mjs          write
//   node scripts/generate.mjs --check  fail if anything is stale (CI)
import fs from 'node:fs';
import path from 'node:path';
import {
  ROOT,
  PRESENT_TOKENS_FILE,
  collectPresentMcpTokenNames,
  departments,
  exists,
  json,
  makeWriter,
  mountedMcpGrants,
  pascal,
  readJson,
  upperSnake,
} from './lib.mjs';

const check = process.argv.includes('--check');
const out = makeWriter(check);
const HEADER = '// GENERATED by scripts/generate.mjs from the role manifest. Do not edit; edit roles/<slug>.json instead.\n';
const skillId = (name) => 'skill_' + name.replace(/-/g, '_');

const presentPath = path.join(ROOT, PRESENT_TOKENS_FILE);
const presentFile = exists(presentPath) ? readJson(presentPath) : { secrets: [] };
const envPath = path.join(ROOT, '.env');
const envFileText = exists(envPath) ? fs.readFileSync(envPath, 'utf8') : null;
const present = collectPresentMcpTokenNames({ present: presentFile.secrets, envFileText });
out.write(PRESENT_TOKENS_FILE, json({
  _comment:
    'Gateway MCP_TOKEN_* names that exist. Role JSON stays complete; generate mounts only these. Values live in .env and Worker secrets, never here.',
  secrets: present,
}));

for (const d of departments()) {
  const rel = (p) => path.join('departments', d.slug, p);
  const bySlug = Object.fromEntries(d.roles.map((r) => [r.slug, r]));

  // ---- one 'use agent' module per role ----
  for (const r of d.roles) {
    const team = (r.delegatesTo ?? []).map((s) => bySlug[s]).filter(Boolean);
    const mcpLiteral = JSON.stringify(mountedMcpGrants(d.slug, r.mcp, present));
    const lines = [
      HEADER + "'use agent';",
      "import { useRole } from '@org/harness';",
      "import type { RoleManifest } from '@org/harness';",
      `import manifest from '../../roles/${r.slug}.json';`,
      ...r.skills.map((s) => `import ${skillId(s)} from '../skills/${s}/SKILL.md';`),
      ...team.map((t) => `import { ${pascal(t.slug)} } from './${t.slug}.ts';`),
      '',
      `export function ${pascal(r.slug)}() {`,
      '  return useRole(',
      `    { manifest: { ...manifest, mcp: ${mcpLiteral} } as RoleManifest, skills: [${r.skills.map(skillId).join(', ')}] },`,
      team.length
        ? '    { team: {\n' + team.map((t) => `      '${t.slug}': { agent: ${pascal(t.slug)}, name: ${JSON.stringify(t.name)} },`).join('\n') + '\n    } },'
        : null,
      '  );',
      '}',
      '',
    ].filter((l) => l !== null);
    out.write(rel(`src/agents/${r.slug}.ts`), lines.join('\n'));
  }

  // ---- app.ts: gateway-bound provider, caller auth, one route per role ----
  const app = [
    '// GENERATED by scripts/generate.mjs. Do not edit.',
    "import { setProvider } from '@flue/runtime';",
    "import { cloudflareBindingProvider } from '@flue/runtime/cloudflare/workers-ai';",
    "import { createAgentRouter } from '@flue/runtime/routing';",
    "import { requireCaller } from '@org/harness';",
    "import { env } from 'cloudflare:workers';",
    "import { Hono } from 'hono';",
    ...d.roles.map((r) => `import { ${pascal(r.slug)} } from './agents/${r.slug}.ts';`),
    '',
    '// Every model call goes through this department\'s own AI Gateway (budgets, logs, rate limits).',
    'setProvider(',
    '  cloudflareBindingProvider({',
    '    binding: env.AI,',
    `    gateway: { id: ${JSON.stringify(d.policy.gatewayId)}, metadata: { department: ${JSON.stringify(d.slug)} } },`,
    '  }),',
    ');',
    '',
    'const app = new Hono();',
    "app.get('/healthz', (c) => c.text('ok'));",
    "app.use('/agents/*', requireCaller());",
    ...d.roles.map((r) => `app.route('/agents/${r.slug}', createAgentRouter(${pascal(r.slug)}));`),
    '',
    'export default app;',
    '',
  ];
  out.write(rel('src/app.ts'), app.join('\n'));

  // ---- build config ----
  const providers = [...new Set(d.policy.models.allowed.map((m) => m.split('/')[0]))];
  out.write(rel('vite.config.ts'), [
    "import { cloudflare } from '@cloudflare/vite-plugin';",
    "import { flue, flueWorkerConfig } from '@flue/vite';",
    "import { defineConfig } from 'vite';",
    '',
    '// flue() must precede cloudflare(). The provider list is derived from policy.json: providers not',
    '// listed are not bundled, so a model outside the department allowlist cannot resolve at all.',
    'export default defineConfig({',
    `  plugins: [flue({ providers: ${JSON.stringify(providers)} }), cloudflare({ config: flueWorkerConfig() })],`,
    '});',
    '',
  ].join('\n'));

  out.write(rel('package.json'), json({
    name: `@org/dept-${d.slug}`,
    private: true,
    type: 'module',
    scripts: { dev: 'vite dev', build: 'vite build', deploy: 'vite build && wrangler deploy' },
    dependencies: { '@flue/runtime': '2.2.2', '@org/harness': '*', '@org/policy-core': '*', hono: '^4.6.0' },
  }));

  out.write(rel('tsconfig.json'), json({
    extends: '../../tsconfig.base.json',
    compilerOptions: { types: ['@flue/runtime'] },
    include: ['src', 'roles'],
  }));

  // ---- wrangler.jsonc: authored once; afterwards ONLY new migrations are appended (never edited/reordered) ----
  const wr = rel('wrangler.jsonc');
  const cfg = exists(path.join(ROOT, wr)) ? readJson(path.join(ROOT, wr)) : {
    $schema: '../../node_modules/wrangler/config-schema.json',
    name: `agents-${d.slug}`,
    compatibility_date: '2026-06-01',
    compatibility_flags: ['nodejs_compat'],
    // Private: reachable only via the router's service binding.
    workers_dev: false,
    preview_urls: false,
    observability: { enabled: true },
    ai: { binding: 'AI' },
    services: [{ binding: 'MCP_GATEWAY', service: 'agents-mcp-gateway' }],
    vars: { DEPARTMENT: d.slug },
    migrations: [],
  };
  const have = new Set(cfg.migrations.map((m) => m.tag));
  for (const r of d.roles) {
    const cls = `Flue${pascal(r.slug)}Agent`;
    const tag = `flue-class-${cls}`;
    if (!have.has(tag)) cfg.migrations.push({ tag, new_sqlite_classes: [cls] });
  }
  out.write(wr, json(cfg));
}

// ---- router: registry + service bindings ----
const registry = {};
const services = [];
for (const d of departments()) {
  const binding = `DEPT_${upperSnake(d.slug)}`;
  registry[d.slug] = { binding, roles: d.roles.map((r) => r.slug) };
  services.push({ binding, service: `agents-${d.slug}` });
}
out.write('packages/router/src/departments.generated.json', json(registry));
const routerWr = 'packages/router/wrangler.jsonc';
const routerPrev = exists(path.join(ROOT, routerWr)) ? readJson(path.join(ROOT, routerWr)) : {};
const emailGroups = exists(path.join(ROOT, 'access-email-groups.json'))
  ? readJson(path.join(ROOT, 'access-email-groups.json'))
  : {};
const vars = { ...(routerPrev.vars ?? {}) };
vars.ACCESS_EMAIL_GROUPS = JSON.stringify(emailGroups);
out.write(routerWr, json({
  $schema: '../../node_modules/wrangler/config-schema.json',
  name: 'agents-router',
  main: 'src/index.ts',
  compatibility_date: '2026-06-01',
  compatibility_flags: ['nodejs_compat'],
  workers_dev: false,
  preview_urls: routerPrev.preview_urls ?? false,
  observability: { enabled: true },
  vars,
  services,
}));

if (check) {
  if (out.diffs.length) {
    console.error(`generate: ${out.diffs.length} stale file(s):\n  ` + out.diffs.slice(0, 15).join('\n  '));
    process.exit(1);
  }
  console.log('generate: up to date');
} else console.log('generate: done');
