// GENERATED by scripts/generate.mjs from the role manifest. Do not edit; edit roles/<slug>.json instead.
'use agent';
import { useRole } from '@org/harness';
import type { RoleManifest } from '@org/harness';
import manifest from '../../roles/application-architect.json';
import skill_software_architecture_playbook from '../skills/software-architecture-playbook/SKILL.md';
import skill_org_conventions from '../skills/org-conventions/SKILL.md';

export function ApplicationArchitect() {
  return useRole(
    { manifest: { ...manifest, mcp: [{"id":"github","tier":"read"},{"id":"cloudflare","tier":"read"}] } as RoleManifest, skills: [skill_software_architecture_playbook, skill_org_conventions] },
  );
}
