// GENERATED by scripts/generate.mjs from the role manifest. Do not edit; edit roles/<slug>.json instead.
'use agent';
import { useRole } from '@org/harness';
import type { RoleManifest } from '@org/harness';
import manifest from '../../roles/chief-architect.json';
import skill_software_architecture_playbook from '../skills/software-architecture-playbook/SKILL.md';
import skill_org_conventions from '../skills/org-conventions/SKILL.md';
import { SolutionsArchitect } from './solutions-architect.ts';
import { ApplicationArchitect } from './application-architect.ts';
import { DataArchitect } from './data-architect.ts';
import { CloudArchitect } from './cloud-architect.ts';
import { IntegrationArchitect } from './integration-architect.ts';
import { SecurityArchitect } from './security-architect.ts';

export function ChiefArchitect() {
  return useRole(
    { manifest: manifest as RoleManifest, skills: [skill_software_architecture_playbook, skill_org_conventions] },
    { team: {
      'solutions-architect': { agent: SolutionsArchitect, name: "Solutions Architect" },
      'application-architect': { agent: ApplicationArchitect, name: "Application Architect" },
      'data-architect': { agent: DataArchitect, name: "Data Architect" },
      'cloud-architect': { agent: CloudArchitect, name: "Cloud Architect" },
      'integration-architect': { agent: IntegrationArchitect, name: "Integration Architect" },
      'security-architect': { agent: SecurityArchitect, name: "Security Architect" },
    } },
  );
}
