// GENERATED by scripts/generate.mjs. Do not edit.
import { setProvider } from '@flue/runtime';
import { cloudflareBindingProvider } from '@flue/runtime/cloudflare/workers-ai';
import { createAgentRouter } from '@flue/runtime/routing';
import { requireCaller } from '@org/harness';
import { env } from 'cloudflare:workers';
import { Hono } from 'hono';
import { QaManager } from './agents/qa-manager.ts';
import { QaEngineer } from './agents/qa-engineer.ts';
import { ManualTester } from './agents/manual-tester.ts';
import { TestAutomationEngineer } from './agents/test-automation-engineer.ts';
import { PerformanceTester } from './agents/performance-tester.ts';
import { SecurityTester } from './agents/security-tester.ts';
import { MobileQaSpecialist } from './agents/mobile-qa-specialist.ts';
import { ApiIntegrationTester } from './agents/api-integration-tester.ts';
import { RegressionTester } from './agents/regression-tester.ts';
import { UatCoordinator } from './agents/uat-coordinator.ts';

// Every model call goes through this department's own AI Gateway (budgets, logs, rate limits).
setProvider(
  cloudflareBindingProvider({
    binding: env.AI,
    gateway: { id: "dept-quality-assurance-testing", metadata: { department: "quality-assurance-testing" } },
  }),
);

const app = new Hono();
app.get('/healthz', (c) => c.text('ok'));
app.use('/agents/*', requireCaller());
app.route('/agents/qa-manager', createAgentRouter(QaManager));
app.route('/agents/qa-engineer', createAgentRouter(QaEngineer));
app.route('/agents/manual-tester', createAgentRouter(ManualTester));
app.route('/agents/test-automation-engineer', createAgentRouter(TestAutomationEngineer));
app.route('/agents/performance-tester', createAgentRouter(PerformanceTester));
app.route('/agents/security-tester', createAgentRouter(SecurityTester));
app.route('/agents/mobile-qa-specialist', createAgentRouter(MobileQaSpecialist));
app.route('/agents/api-integration-tester', createAgentRouter(ApiIntegrationTester));
app.route('/agents/regression-tester', createAgentRouter(RegressionTester));
app.route('/agents/uat-coordinator', createAgentRouter(UatCoordinator));

export default app;
