// GENERATED by scripts/generate.mjs from the role manifest. Do not edit; edit roles/<slug>.json instead.
'use agent';
import { useRole } from '@org/harness';
import type { RoleManifest } from '@org/harness';
import manifest from '../../roles/information-architect.json';
import skill_user_research_experience_playbook from '../skills/user-research-experience-playbook/SKILL.md';
import skill_org_conventions from '../skills/org-conventions/SKILL.md';

export function InformationArchitect() {
  return useRole(
    { manifest: { ...manifest, mcp: [] } as RoleManifest, skills: [skill_user_research_experience_playbook, skill_org_conventions] },
  );
}
