// GENERATED by scripts/generate.mjs from the role manifest. Do not edit; edit roles/<slug>.json instead.
'use agent';
import { useRole } from '@org/harness';
import type { RoleManifest } from '@org/harness';
import manifest from '../../roles/ux-research-lead.json';
import skill_user_research_experience_playbook from '../skills/user-research-experience-playbook/SKILL.md';
import skill_org_conventions from '../skills/org-conventions/SKILL.md';
import { UserResearcher } from './user-researcher.ts';
import { BehavioralAnalyst } from './behavioral-analyst.ts';
import { AccessibilitySpecialist } from './accessibility-specialist.ts';
import { InformationArchitect } from './information-architect.ts';
import { UsabilityTester } from './usability-tester.ts';

export function UxResearchLead() {
  return useRole(
    { manifest: { ...manifest, mcp: [] } as RoleManifest, skills: [skill_user_research_experience_playbook, skill_org_conventions] },
    { team: {
      'user-researcher': { agent: UserResearcher, name: "User Researcher" },
      'behavioral-analyst': { agent: BehavioralAnalyst, name: "Behavioral Analyst" },
      'accessibility-specialist': { agent: AccessibilitySpecialist, name: "Accessibility Specialist" },
      'information-architect': { agent: InformationArchitect, name: "Information Architect" },
      'usability-tester': { agent: UsabilityTester, name: "Usability Tester" },
    } },
  );
}
