// GENERATED by scripts/generate.mjs from the role manifest. Do not edit; edit roles/<slug>.json instead.
'use agent';
import { useRole } from '@org/harness';
import type { RoleManifest } from '@org/harness';
import manifest from '../../roles/pmo-analyst.json';
import skill_project_management_playbook from '../skills/project-management-playbook/SKILL.md';
import skill_org_conventions from '../skills/org-conventions/SKILL.md';

export function PmoAnalyst() {
  return useRole(
    { manifest: { ...manifest, mcp: [] } as RoleManifest, skills: [skill_project_management_playbook, skill_org_conventions] },
  );
}
