// GENERATED by scripts/generate.mjs from the role manifest. Do not edit; edit roles/<slug>.json instead.
'use agent';
import { useRole } from '@org/harness';
import type { RoleManifest } from '@org/harness';
import manifest from '../../roles/program-manager.json';
import skill_project_management_playbook from '../skills/project-management-playbook/SKILL.md';
import skill_org_conventions from '../skills/org-conventions/SKILL.md';
import { ProjectManager } from './project-manager.ts';
import { TechnicalProjectManager } from './technical-project-manager.ts';
import { DeliveryManager } from './delivery-manager.ts';
import { ResourceManager } from './resource-manager.ts';
import { PmoAnalyst } from './pmo-analyst.ts';
import { PortfolioManager } from './portfolio-manager.ts';

export function ProgramManager() {
  return useRole(
    { manifest: manifest as RoleManifest, skills: [skill_project_management_playbook, skill_org_conventions] },
    { team: {
      'project-manager': { agent: ProjectManager, name: "Project Manager" },
      'technical-project-manager': { agent: TechnicalProjectManager, name: "Technical Project Manager" },
      'delivery-manager': { agent: DeliveryManager, name: "Delivery Manager" },
      'resource-manager': { agent: ResourceManager, name: "Resource Manager" },
      'pmo-analyst': { agent: PmoAnalyst, name: "PMO Analyst" },
      'portfolio-manager': { agent: PortfolioManager, name: "Portfolio Manager" },
    } },
  );
}
